version: "3.9"

services:
  redis:
    container_name: dg-panel-redis
    command: redis-server /etc/redis/redis.conf
    image: redis:alpine
    restart: unless-stopped
    #    ports:
    #      - 6379:6379
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf
  
  backend:
    image: registry-gitlab.pieter557.dscloud.me/degrens-21/panel/server:latest
    container_name: dg-panel-server
    restart: unless-stopped
    depends_on:
      - redis
  
  web:
    image: registry-gitlab.pieter557.dscloud.me/degrens-21/panel/webui:latest
    container_name: dg-panel-web
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  redis-data:
  mariadb-data:

networks:
  default:
    name: dg-panel-net
