version: "3.9"

services:
  redis:
    container_name: dg-panel-redis
    command: redis-server /etc/redis/redis.conf
    image: redis:alpine
    restart: unless-stopped
    #    ports:
    #      - 6379:6379
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf
  
  mariadb:
    container_name: dg-panel-mariadb
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: degrens-panel
      MYSQL_USER: panel
      MYSQL_PASSWORD: panel
    #    ports:
    #      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
  
  backend:
    image: registry-gitlab.pieter557.dscloud.me/degrens-21/panel/server:latest
    container_name: dg-panel-server
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
  
  web:
    image: registry-gitlab.pieter557.dscloud.me/degrens-21/panel/webui:latest
    container_name: dg-panel-web
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  redis-data:
  mariadb-data:

networks:
  default:
    name: dg-panel-net
